// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CustomerPersonalInformation struct {
	ID                   pgtype.UUID
	Title                pgtype.Text
	FirstName            pgtype.Text
	MiddleName           pgtype.Text
	LastName             pgtype.Text
	FirstNameInEnglish   pgtype.Text
	MiddleNameInEnglish  pgtype.Text
	LastNameInEnglish    pgtype.Text
	DateOfBirth          pgtype.Timestamptz
	CountryOfBirthID     pgtype.Text
	GenderID             pgtype.Text
	IsPoliticallyExposed pgtype.Bool
	IsUsPerson           pgtype.Bool
	MaritalStatusID      pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}
