// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomer = `-- name: GetCustomer :one
SELECT id, title, first_name, middle_name, last_name, first_name_in_english, middle_name_in_english, last_name_in_english, date_of_birth, country_of_birth_id, gender_id, is_politically_exposed, is_us_person, marital_status_id, created_at, updated_at FROM customer_personal_information
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id pgtype.UUID) (CustomerPersonalInformation, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i CustomerPersonalInformation
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.FirstNameInEnglish,
		&i.MiddleNameInEnglish,
		&i.LastNameInEnglish,
		&i.DateOfBirth,
		&i.CountryOfBirthID,
		&i.GenderID,
		&i.IsPoliticallyExposed,
		&i.IsUsPerson,
		&i.MaritalStatusID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
